### ISSUE TITLE
Python 2 requirement

### ISSUE THREAD

**Issue by ivan-pi** [UCL-CCS/HemePure-GPU#6]
Attempting to build this project from source, I noticed the packaged CTemplate version has a Python 2 build/installation requirement:

```
[ 70%] Performing build step for 'CTemplate'
  File "/home/HemePure-GPU/dep/build/CTemplate-prefix/src/CTemplate/./src/htmlparser/generate_fsm.py", line 309
    print '\n'.join((self._CreateHeader(),
```

There has only been one new CTemplate release (v2.4), but I haven't yet inspected if it was replaced with Python 3.

**Comment by ivan-pi** [comment]
Okay, it looks like the switch was made in v2.4 of CTemplate: https://github.com/OlafvdSpek/ctemplate/commit/ee11ba100a909bff3698e1332ffb133a2ea9b3ee

Since Python 2 is now [unsupported](https://www.python.org/doc/sunset-python-2/), some environments don't provide it anymore. 

Replacing the old tarball (https://github.com/UCL-CCS/HemePure-GPU/blob/master/dep/src/ctemplate-2.3.tar.gz) with the new one (https://github.com/OlafvdSpek/ctemplate/releases/tag/ctemplate-2.4) would be the solution.

**Comment by ivan-pi** [comment]
Replacing the tarball with the new version or simply using the `CTEMPLATE_TARBALL` variable doesn't work, because the CMake script expects to find an executable `configure`:

```
[ 70%] Creating directories for 'CTemplate'
[ 75%] Performing download step (download, verify and extract) for 'CTemplate'
-- Downloading...
   dst='/home/HemePure-GPU/dep/build/CTemplate-prefix/src/ctemplate-2.4.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='http://github.com/OlafvdSpek/ctemplate/archive/ctemplate-2.4.tar.gz'
-- Downloading... done
-- extracting...
     src='/home/HemePure-GPU/dep/build/CTemplate-prefix/src/ctemplate-2.4.tar.gz'
     dst='/home/HemePure-GPU/dep/build/CTemplate-prefix/src/CTemplate'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 79%] No update step for 'CTemplate'
[ 83%] Performing patch step for 'CTemplate'
noalign
novacopy
[ 87%] Performing configure step for 'CTemplate'
/bin/sh: /home/HemePure-GPU/dep/build/CTemplate-prefix/src/CTemplate/configure: No such file or directory
make[2]: *** [CMakeFiles/CTemplate.dir/build.make:92: CTemplate-prefix/src/CTemplate-stamp/CTemplate-configure] Error 127
make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/CTemplate.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

The configure script is only available after `./autogen.sh` has been run, which must have been the case in the current tarball. 

To fix this I had to patch this line:

https://github.com/UCL-CCS/HemePure-GPU/blob/a398c30b45ebbf8461c8e76029827173b52d7cd7/dep/CMakeLists.txt#L229

```diff
-	CONFIGURE_COMMAND	<SOURCE_DIR>/configure --prefix=<INSTALL_DIR> ${CTEMPLATE_CONFIGURE_OPTIONS}
+	CONFIGURE_COMMAND	<SOURCE_DIR>/autogen.sh && <SOURCE_DIR>/configure --prefix=<INSTALL_DIR> ${CTEMPLATE_CONFIGURE_OPTIONS} 
```

**Comment by ivan-pi** [comment]
I was finally able to build CTemplate now 🚀 

```
[100%] Completed 'CTemplate'
[100%] Built target CTemplate
```

It did however choke with the NVIDIA `nvc/nvc++` compiler, so I switched to `gcc` for the dependency libraries.

**Comment by izacharo** [comment]
Hi Ivan,

Another alternative is to use python's function 2to3 to convert the python
scripts that cause the problem.

So when it complains about the python 2 files (there will be 2 in total)
you can do the conversion by using
2to3 - w path_to_python_file/python_file.py

You will do that twice.

I will get back to you in a while with more details regarding these files.

Best,
Ioannis

**Comment by ivan-pi** [comment]
Thanks for the tip, I was not aware of the 2to3 tool. 👍🏻  

The environment I'm working in is somewhat restricted, I have no pip access, and only Python 3.9 is available by default. Not even automake/autoreconf were present to build CTemplate, but I got hold of them through a module. 

As far as I can see, the only difference in CTemplate v2.4 is the switch to Python 3. It is also used in HemePure-CPU Spack build: https://github.com/compbiomedeu/compbiomed-spack/blob/main/packages/ctemplate/package.py#L33

**Comment by izacharo** [comment]
I understand what pain this can be... On a different note I got rid of the memory allocations inside the GPU kernels that were causing a problem with porting to oneapi. So I should be able to make progress on that task soon. I just need to finalize a few other things this week with the hipified code first. I will keep you posted Best, Ioannis Sent from my phone-------- Original message --------From: Ivan Pribec ***@***.***>Date: Wed, 3 May 2023, 13:35To: UCL-CCS/HemePure-GPU ***@***.***>Cc: izacharo ***@***.***>, Comment ***@***.***>Subject: Re: [UCL-CCS/HemePure-GPU] Python 2 requirement (Issue #6)
Thanks for the tip, I was not aware of the 2to3 tool. 👍🏻
The environment I'm working in is somewhat restricted, I have no pip access, and only Python 3.9 is available by default. Not even automake/autoreconf were present to build CTemplate, but I got hold of them through a module.
As far as I can see, the only difference in CTemplate v2.4 is the switch to Python 3. It is also used in HemePure-CPU Spack build: https://github.com/compbiomedeu/compbiomed-spack/blob/main/packages/ctemplate/package.py#L33

**Comment by ivan-pi** [comment]
I think this issue is also resolved by #9? cc @benczaja

**Comment by benczaja** [comment]
Yes it should be (@ivan-pi). Though I think that the HIP branch (https://github.com/UCL-CCS/HemePure-GPU/tree/HIP) still does not have the merge
